### ISSUE TITLE
Upgrading from 9.x to 10.x introduces error within VS Code: typescript with invalid interface loaded as resolver

### ISSUE THREAD

**Issue by ffxsam** [nuxt/eslint#221]
When I upgrade `@nuxtjs/eslint-config-typescript` to 10.0.0, I see this error in VS Code:

<img width="770" alt="CleanShot 2022-07-04 at 13 13 47" src="https://user-images.githubusercontent.com/12532733/177204761-aaf31e9e-5d02-480c-8731-783e8ff074fc.png">

Relevant config:

```js
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    '@vue/typescript/recommended',
    '@nuxtjs/eslint-config-typescript',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
  },
  plugins: ['vue', '@typescript-eslint'],
```

**Comment by antfu** [comment]
It sounds like a vue parser issue, which I believe it's already fixed in the latest version. Closing for now.
