### ISSUE TITLE
Does not lint *.ts files in `plugins/`, `server/` etc. 

### ISSUE THREAD

**Issue by safejace** [nuxt/eslint#318]
one of the features is "Nuxt-specific rules for pages, components and more."

does the more include the `*.ts` files, cuz right now it's not working for me :(

if not, is there a recommended way to lint and entire Nuxt project?

**Comment by antfu** [comment]
It's deps on if you want only `linting` or also `formatting`. Nuxt eslint-config is unopinionated, meaning it does not format your files. You can use a formatter like Prettier along side, or you can try to add https://eslint.style/ rules (which is out-of-scope of this config)

**Comment by antfu** [comment]
With https://github.com/nuxt/eslint/pull/332 it should improve the situation. We will also try to introduce a more "opiniated" config for opt-in as we go.
