### ISSUE TITLE
@nuxt/eslint-config is not picking up Nuxt globals in JS files

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/eslint#321]
~~Everything works fine with `@nuxt/eslint-config`, but as soon as you swap it out for `@nuxt/eslint-config-typescript`, eslint will tell you that it can't find `@nuxt/eslint-config-typescript` to extend from:~~

~~`Error: Failed to load config "@nuxt/eslint-config-typescript" to extend from.`~~

**Comment by TheDutchCoder** [comment]
Ah boy, the module was renamed from `@nuxt` to `@nuxtjs` namespace but the docs haven't updated properly I think?

**Comment by TheDutchCoder** [comment]
Okay, apparently this isn't supposed to be used with Nuxt3, which leads me to the original problem I'm experiencing:

When using `@nuxt/eslint-config` and you have a TS and JS project, eslint works fine for the TS files, but it does not pick up any of the Nuxt globals in JS files.

**Comment by cco3** [comment]
Do you have globals picked up from ts files?  I don't have it picking up globals from anywhere.

**Comment by MrStanDu33** [comment]
Same here, Even after generating TS styles (`nuxi prepare`), and using `@nuxt/eslint-config` as last extend inside my `.eslintrc.js` config file.
