### ISSUE TITLE
[Docs] description in Prettier section is a little misleading

### ISSUE THREAD

**Issue by kingyue737** [nuxt/eslint#342]
### Environment

ignore

### Package

None

### Reproduction

ignore

### Describe the bug

> This module does not enable any stylistic/formatting rules by default. You can use Prettier alongside directly.

`@nuxt/eslint` includes some rules in `eslint-plugin-vue` which conflicts with prettier like `vue/max-attributes-per-line`. Therefore, we cannot use Prettier alongside "directly", still need to turn off those rules manually or via `eslint-config-prettier`.

**Comment by antfu** [comment]
From my point of view I think it make sense for us to disable `vue/max-attributes-per-line` (and any other formatting rules) by default

**Comment by meirroth** [comment]
@antfu Thank you for adding the FAQs, really helpful! 
I think Prettier section can use extra instructions or an example project with prettier working along side @nuxt/eslint, considering how popular Eslint + Prettier is.

**Comment by cannap** [comment]
> For anyone who comes across this issue looking to integrate Prettier with @nuxt/eslint (and @intlify/eslint-plugin-vue-i18n), here's my working config, after hours of trial and error:
> 
> ```
> import eslintConfigPrettier from 'eslint-config-prettier'
> import prettierPlugin from 'eslint-plugin-prettier'
> import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended'
> import vueI18n from '@intlify/eslint-plugin-vue-i18n'
> import withNuxt from './.nuxt/eslint.config.mjs'
> 
> export default withNuxt([
>   ...vueI18n.configs['flat/recommended'],
>   {
>     plugins: {
>       prettier: prettierPlugin,
>     },
>     rules: {
>       ...eslintConfigPrettier.rules,
>       ...eslintPluginPrettierRecommended.rules,
> 
>       'no-console': 'warn',
>       'vue/multi-word-component-names': 'off',
>     },
>     settings: {
>       'vue-i18n': {
>         localeDir: './localization/*.json',
>         messageSyntaxVersion: '^9.0.0',
>       },
>     },
>   },
> ])
> ```
> 
> Sources that helped: #387 and https://eslint-plugin-vue-i18n.intlify.dev/started.html

i tried do i have to enable stylistic and formatter prettiert?

**Comment by meirroth** [comment]
@cannap No need for stylistic if your using prettier. See here how I added and configured prettier to work with this module: https://github.com/meirroth/nuxtboiler/commit/181618f3dc848e830163b80990d109c1f3e7afef

**Comment by tillsanders** [comment]
I have another conflict like this with the rule `vue/html-self-closing`. Would it make sense to exclude this rule as well?
