### ISSUE TITLE
Prettier setup guide

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/eslint#351]
### Describe the feature

... with particular focus on the following: https://github.com/prettier/eslint-config-prettier#eslintconfigjs-flat-config-plugin-caveat

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by antfu** [comment]
I don't think we are hitting that caveat - what do you want to address?

**Comment by DamianGlowala** [comment]
You're right, inspected the configs with DevTools and the original prefix is kept (mistakenly assumed we rename the rules to `ts/`). I think this might be closed.
