### ISSUE TITLE
Add more built-in presets for opt-in

### ISSUE THREAD

**Issue by antfu** [nuxt/eslint#353]
### Describe the feature

We could have a few more opinionated presets on top of our unopinionated foundation for people to opt in. Providing the "out-of-box" config for most of the users

Namely:

- https://github.com/un-ts/eslint-plugin-import-x for imports linting
- https://www.npmjs.com/package/eslint-plugin-unused-imports for unused-imports with auto-fix
- https://github.com/ota-meshi/eslint-plugin-jsonc I personally find it very helpful to sort package.json and tsconfig.json in a consistent order - not sure if that would be a bit too much for Nuxt

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by danielroe** [comment]
Would maybe also be useful to have a module-author configuration that takes module configuration into account? (This could also be implemented/integrated with `@nuxt/module-builder`, perhaps?)
