### ISSUE TITLE
Add `strict` option to `NuxtESLintConfigOptions` for enforcing `typescript-eslint` strict rules

### ISSUE THREAD

**Issue by chadwickellis** [nuxt/eslint#362]
### Describe the feature

To enhance the TypeScript development experience within Nuxt projects, I propose adding a `strict` option to the `NuxtESLintConfigOptions`. This new option will enable the enforcement of `typescript-eslint` strict rules, ensuring stricter type checks and promoting best coding practices. Currently, developers can enable `typescript-eslint` strict rules manually by modifying the ESLint configuration as follows:

```javascript
import { createConfigForNuxt, defineFlatConfigs } from '@nuxt/eslint-config/flat'
import pluginTs from '@typescript-eslint/eslint-plugin'

export default defineFlatConfigs(
  createConfigForNuxt().then((configs) => {
    return configs.map((config) => {
      return config.name === 'nuxt:typescript'
        ? {
            ...config,
            rules: {
              ...config.rules,
              ...pluginTs.configs.strict.rules,
            },
          }
        : config
    })
  }),
)
```

However, this process is not straightforward and can be cumbersome, especially for new developers or larger projects. Implementing a dedicated `strict` option would simplify this configuration process, improve code quality, and help developers adhere to TypeScript's strictest standards. This enhancement aligns with the ongoing efforts to strengthen type safety and code consistency in Nuxt applications.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by antfu** [comment]
We enabled it by default now, with an option to disable it: https://github.com/nuxt/eslint/commit/ae2d78af95dbe9905a5e1c35b26e40144b55b610

Thanks for bringing this up
