### ISSUE TITLE
Argument of type is not assignable to parameter within `withNuxt` with `antfu` config

### ISSUE THREAD

**Issue by nandordudas** [nuxt/eslint#364]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      app, devServer, eslint, modules, runtimeConfig, testUtils
- Runtime Modules:  @nuxt/eslint@0.3.0-beta.3, @vueuse/nuxt@10.9.0, @nuxtjs/color-mode@3.3.3, @nuxt/ui@2.15.0, @nuxt/test-utils/module@3.12.0, @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Package

@nuxt/eslint

### Reproduction

Install dependencies

```bash
pnpm add -D @nuxt/eslint eslint @antfu/eslint-config eslint-ts-patch eslint@npm:eslint-ts-patch
```

`nuxt.config.ts`

```ts
export default defineNuxtConfig({
  modules: [
    '@nuxt/eslint'
  ],
  eslint: {
    config: {
      standalone: false,
    }
  }
})
```

`eslint.config.ts`

```ts
import antfu from '@antfu/eslint-config'

import withNuxt from './.nuxt/eslint.config.mjs'

const antfuConfig = antfu({
  rules: {
    'complexity': ['error', 5],
    'perfectionist/sort-objects': 'error',
  },
})
  .override('antfu:imports', {
    rules: {
      'import/order': ['error', {
        'alphabetize': { caseInsensitive: true, order: 'asc' },
        'groups': ['external', 'builtin', ['sibling', 'parent'], 'index', 'object'],
        'newlines-between': 'always',
        'pathGroups': [
          { group: 'external', pattern: '~/**', position: 'after' },
        ],
      }],
    },
  })
  .toConfigs()

// @ts-expect-error Argument of type 'Promise<UserConfigItem[]>' is not assignable to parameter of type 'Awaitable<FlatConfig | FlatConfig[]>'.
export default withNuxt(antfuConfig)
```

Run typecheck or just see the error in the `VS Code`

```bash
npx nuxi typecheck
```

### Describe the bug

I've got Typescript error `Argument of type 'Promise<UserConfigItem[]>' is not assignable to parameter of type 'Awaitable<FlatConfig | FlatConfig[]>'.` in my `eslint.config.ts` file with the provided configuration.

### Additional context

Following the local modifications, the error vanished due to alias.

> [!NOTE]
> It just a temporary solution from my side.

[Custom Config Presets](https://eslint.nuxt.com/packages/module#custom-config-presets)

```ts
import antfu from '@antfu/eslint-config'
import type { FlatConfig } from '@nuxt/eslint-config/flat'

import withNuxt from './.nuxt/eslint.config.mjs'

const antfuConfig = antfu(...).toConfigs() as FlatConfig

export default withNuxt(antfuConfig)
```

**Comment by antfu** [comment]
Actually, with `@antfu/eslint-config` I'd suggest you to do:

```ts
import antfu from '@antfu/eslint-config'
import nuxt from './.nuxt/eslint.config.mjs'

export default antfu(
  // ...
  nuxt(),
)
```

As `antfu()` is actually a higher level with more specific types. I am still figuring out the best way for them to works the best together.

**Comment by nandordudas** [comment]
Thank you Anthony, I'll try it later

**Comment by nikolasdas** [comment]
@antfu This does not work unfortunately :/
`Error: Key "plugins": Cannot redefine plugin "ts".`

**Comment by antfu** [comment]
@nikolasdas Please create another issue with a minimal reproduction, thanks

**Comment by nandordudas** [comment]
It works me fine in teh CLI and `VS Code` too, thanks.

> [!NOTE]
> The `ESLint patch` has been removed cause of unnecessary dependency, so I'm using the `ESModule` configuration instead.

`eslint.config.mjs`

```js
// @ts-check
import antfu from '@antfu/eslint-config'

import nuxt from './.nuxt/eslint.config.mjs'

export default antfu(
  {
    rules: {
      'complexity': ['error', 5],
      'nuxt/prefer-import-meta': 'error',
      'perfectionist/sort-objects': 'error',
      'ts/explicit-function-return-type': 'error',
    },
  },
)
  .override(
    'antfu:imports',
    {
      rules: {
        'import/order': ['error', {
          'alphabetize': { caseInsensitive: true, order: 'asc' },
          'groups': ['external', 'builtin', ['sibling', 'parent'], 'index', 'object'],
          'newlines-between': 'always',
          'pathGroups': [
            { group: 'external', pattern: '~/**', position: 'after' },
          ],
        }],
      },
    },
  )
  .append(nuxt())
```
