### ISSUE TITLE
Configuration tutorial cannot be used

### ISSUE THREAD

**Issue by ye21st** [nuxt/eslint#392]
### Environment

Nuxt project info:                                                                                                                                                               23:09:08

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      devtools, modules, tailwindcss, colorMode, i18n, eslint
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxtjs/color-mode@3.4.0, @nuxtjs/i18n@8.3.0, @nuxt/eslint@0.3.6
- Build Modules:    -
------------------------------

### Package

None

### Reproduction

[URL](https://codesandbox.io/p/devbox/mystifying-poincare-7328rv?file=%2Fpackage.json%3A7%2C23&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluvdq25n0007356h37ipfhvn%2522%252C%2522sizes%2522%253A%255B63.507214426353045%252C36.492785573646955%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluvdq25n0002356h4upy8z2u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluvdq25n0004356hhf6v6du0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluvdq25n0006356hb4fra32p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluvdq25n0002356h4upy8z2u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluvdq25n0001356hd595i1e1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluvdr324003n356hsi3m5l09%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A23%257D%255D%257D%255D%252C%2522id%2522%253A%2522cluvdq25n0002356h4upy8z2u%2522%252C%2522activeTabId%2522%253A%2522cluvdr324003n356hsi3m5l09%2522%257D%252C%2522cluvdq25n0006356hb4fra32p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluvdq25n0005356ho9q2v4kx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Ffr%2522%257D%255D%252C%2522id%2522%253A%2522cluvdq25n0006356hb4fra32p%2522%252C%2522activeTabId%2522%253A%2522cluvdq25n0005356ho9q2v4kx%2522%257D%252C%2522cluvdq25n0004356hhf6v6du0%2522%253A%257B%2522id%2522%253A%2522cluvdq25n0004356hhf6v6du0%2522%252C%2522activeTabId%2522%253A%2522cluvdyro600mf356h5k3ocli5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluvdq25n0003356h6mddoz6x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cluvdyro600mf356h5k3ocli5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluvdys7g033mddg7hatign8h%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

cant't run  ``` eslint .```

### Logs

```shell-script
Oops! Something went wrong! :(

ESLint: 9.0.0

Error: ESLintFlatConfigUtils: Failed to locate config with name "nuxt/typescript"
Available names are: nuxt/vue/single-root, nuxt/rules, nuxt/stylistic, nuxt/disables/routes, nuxt/import-globals
    at getConfigIndex (file:///E:/Code/Company/Focre-Official-Website/node_modules/.pnpm/eslint-flat-config-utils@0.2.2/node_modules/eslint-flat-config-utils/dist/index.mjs:272:13)
    at file:///E:/Code/Company/Focre-Official-Website/node_modules/.pnpm/eslint-flat-config-utils@0.2.2/node_modules/eslint-flat-config-utils/dist/index.mjs:164:21
    at FlatConfigComposer.toConfigs (file:///E:/Code/Company/Focre-Official-Website/node_modules/.pnpm/eslint-flat-config-utils@0.2.2/node_modules/eslint-flat-config-utils/dist/index.mjs:237:23)
    at async calculateConfigArray (E:\Code\Company\Focre-Official-Website\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\eslint\eslint.js:395:28)
    at async ESLint.lintFiles (E:\Code\Company\Focre-Official-Website\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\eslint\eslint.js:814:25)
    at async Object.execute (E:\Code\Company\Focre-Official-Website\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\cli.js:461:23)
    at async main (E:\Code\Company\Focre-Official-Website\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\bin\eslint.js:165:22)
 ELIFECYCLE  Command failed with exit code 2.

Process finished with exit code 1
```

**Comment by antfu** [comment]
You disabled `standalone` - naturally, you don't have `nuxt/typescript` to override.

**Comment by Dylan0916** [comment]
I encountered the same issue.
I didn't disable `standalone`. I even explicitly added `{ standalone: true }`, but I'm still getting the same error
