### ISSUE TITLE
CheckerOptions.fix

### ISSUE THREAD

**Issue by amery** [nuxt/eslint#394]
### Describe the feature

`NuxtConfig['eslint']` doesn't allow `fix?: boolean` anywhere, I would expect it as part of CheckerOptions to do something as follows:

```ts
const autoFix = true;

export default defineNuxtConfig({
  modules: [
    ...modules,
    '@nuxt/eslint',
  ],
  eslint: {
    checker: {
      lintOnStart: autoFix,
      fix: autoFix, // <--- wanted
    },
  },
});
```

fix was supported by the legacy module.
example repo: https://github.com/amery/go-nuxt-template/tree/main/web/client

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by amery** [comment]
that test repo has `@stylistic/semi` set to always, so seeing `fix: true` doesn't work is easy to reproduce.

**Comment by antfu** [comment]
It works for me -- it seems that it's just the type is not exposed, but the runtime it does work
