### ISSUE TITLE
[NUXT] Cannot write file `eslint.config.mjs` because it would overwrite input file.

### ISSUE THREAD

**Issue by mitjans** [nuxt/eslint#414]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.6
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  nuxt-edgedb-module@0.0.46, @vueuse/nuxt@10.9.0, @nuxt/eslint@0.3.10, @nuxtjs/tailwindcss@6.12.0
- Build Modules:    -
------------------------------

### Package

@nuxt/eslint

### Reproduction

1. Create a new Nuxt project
2. Install `@nuxt/eslint` module
3. Create an API endpoint

### Describe the bug

Nitro is not setting `noEmit: true` in the server `tsconfig.json` file by default.

**Comment by antfu** [comment]
https://github.com/nuxt/eslint/pull/415 

I couldn't reproduce this on my side, and this should be in the upstream's scope.
