### ISSUE TITLE
docs: document `autoInit`

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/eslint#427]
### Describe the feature

I've been wondering if there is a way to turn off `eslint.config.js` generation and only found the option when looking at the source code. I think it should be documented.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by antfu** [comment]
Would you like to send a quick PR? Thanks

**Comment by dargmuesli** [comment]
Sure! Done :heavy_check_mark:
