### ISSUE TITLE
docs: `i-ph-lightbulb-duotone` is not displayed

### ISSUE THREAD

**Issue by shinGangan** [nuxt/eslint#430]
### 🐞 Report

The `callout` component icon is not displayed as shown below.

---
![image](https://github.com/nuxt/eslint/assets/44604921/905c5c56-28e8-4d43-ae90-573c37e06438)
---

After conducting an investigation, we confirmed that the icons were not displayed in all places where `callout{icon="i-ph-lightbulb-duotone"}` was used.

### 🗒️ Note

The existence of the icon has been confirmed.

- https://icon-sets.iconify.design/ph/lightbulb-duotone/

**Comment by kingyue737** [comment]
![image](https://github.com/nuxt/eslint/assets/40021217/4891dccd-5785-45a9-9676-430db283b872)

seems good currently

**Comment by shinGangan** [comment]
Looks good to me so far. 👍 

@kingyue737 , thanks for teaching me. 🙏

**Comment by shinGangan** [comment]
It's now resolved so I'm closing it.
