### ISSUE TITLE
Include `eslint-plugin-regexp` in `tooling` preset

### ISSUE THREAD

**Issue by antfu** [nuxt/eslint#432]
### Describe the feature

https://github.com/ota-meshi/eslint-plugin-regexp is a great tool to analyze and provide feedback to potential regex mistakes or slow regexes. I believe it's great tools for module author to catch those warnings during development.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by antfu** [comment]
/cc @danielroe What do you think? If we do, should we do a minor bump? (in that case I think we might figure out a versioning policy for this repo and mention it in the docs)

For my own config, I don't consider adding rules as breaking: https://github.com/antfu/eslint-config#versioning-policy

But since this could be a bit destructive, I want to double-check and ensure they way we do this aligns with Nuxt's philosophy.

Example of these rules in nuxt/nuxt: https://github.com/nuxt/nuxt/pull/27207

**Comment by danielroe** [comment]
This seems good to me - (nice plugin!) - and I think a minor bump should be fine. Do you think we could provide a single flag to disable, e.g.`regepx: false`?
