### ISSUE TITLE
Cannot find package 'vite-plugin-eslint2'

### ISSUE THREAD

**Issue by ChamperNet** [nuxt/eslint#438]
### Environment

Windows 10 [localhost]
Node.js: v18.20.2

### Package

@nuxt/eslint

### Reproduction

Trying to implement the new @nuxt/eslint package:

1) added a dev dependency
2) created eslint.config.mjs with basic values (from the example in doc)

package.json:
```
  "dependencies": {
    "@nuxt/fonts": "^0.7.0",
    "@nuxt/image": "^1.7.0",
    "@nuxt/ui": "^2.16.0",
    "@nuxtjs/seo": "^2.0.0-rc.10",
    "@nuxtjs/strapi": "^1.12.0",
    "@pinia/nuxt": "^0.5.1",
    "nuxt": "^3.11.2",
    "nuxt-swiper": "^1.2.2",
    "sass": "^1.74.1",
    "sass-loader": "^14.1.1",
    "vue": "^3.4.27",
    "vue-router": "^4.3.2"
  },
  "devDependencies": {
    "@nuxt/eslint": "^0.3.13",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "typescript": "^5.4.5"
  }
}
```

### Describe the bug

After ```yarn dev``` I've got an error:
```
 [unhandledRejection] Cannot find package 'vite-plugin-eslint2' imported from D:\<Path>\node_modules\@nuxt\eslint\dist\chunks\checker.mjs
```

### Additional context

Used ways to fix a bug:

- removed node_modules directory and installed again
- cleaned yarn cache
- trying to install in "clean" new project

No effect has been achieved.

### Logs

```shell-script
at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at packageResolve (node:internal/modules/esm/resolve:916:9)
  at moduleResolve (node:internal/modules/esm/resolve:973:20)
  at defaultResolve (node:internal/modules/esm/resolve:1193:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
  at ModuleLoader.import (node:internal/modules/esm/loader:336:34)
  at importModuleDynamically (node:internal/modules/esm/translators:143:35)
  at importModuleDynamicallyCallback (node:internal/modules/esm/utils:176:14)
...
```
```

**Comment by shinGangan** [comment]
Hi @ChamperNet .
The documentation states the following, have you tried this yet? ( [links](https://eslint.nuxt.com/packages/module#dev-server-checker) )

> You will need to install extra dependencies vite-plugin-eslint2 for Vite, or eslint-webpack-plugin if you are using the [Webpack builder](https://nuxt.com/docs/getting-started/configuration#with-webpack) for Nuxt 3.

If you are trying this, you may need to dig a little deeper into the problem.

---

The same error occurs in my environment (mac os, Node20, pnpm) when `vite-plugin-eslint2` is not installed.
After the installation is complete, the error no longer occurs.

**Comment by ChamperNet** [comment]
> Hi @ChamperNet . The documentation states the following, have you tried this yet? ( [links](https://eslint.nuxt.com/packages/module#dev-server-checker) )
> 
> > You will need to install extra dependencies vite-plugin-eslint2 for Vite, or eslint-webpack-plugin if you are using the [Webpack builder](https://nuxt.com/docs/getting-started/configuration#with-webpack) for Nuxt 3.
> 
> If you are trying this, you may need to dig a little deeper into the problem.
> 
> The same error occurs in my environment (mac os, Node20, pnpm) when `vite-plugin-eslint2` is not installed. After the installation is complete, the error no longer occurs.

Yes, you are completely right. I forgot to add a dev dependency ```vite-plugin-eslint2```.
Problem solved.

**Comment by shinGangan** [comment]
@ChamperNet 

I'm glad your problem was resolved to! 😀

**Comment by ChamperNet** [comment]
> @ChamperNet
> 
> I'm glad your problem was resolved to! 😀

Apparently, I was in a hurry.

```
 ERROR  [uncaughtException] Failed to initialize ESLint. Have you installed and configured correctly? Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'eslint
```

After adding ```vite-plugin-eslint2``` and ```yarn dev```

package.json:
```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix"
  },
  "dependencies": {
    "@nuxt/fonts": "^0.7.0",
    "@nuxt/image": "^1.7.0",
    "@nuxt/ui": "^2.16.0",
    "@nuxtjs/i18n": "^8.3.0",
    "@nuxtjs/seo": "^2.0.0-rc.10",
    "@nuxtjs/strapi": "^1.12.0",
    "@pinia/nuxt": "^0.5.1",
    "nuxt": "^3.11.2",
    "nuxt-swiper": "^1.2.2",
    "sass": "^1.74.1",
    "sass-loader": "^14.1.1",
    "vue": "^3.4.27",
    "vue-markdown-render": "^2.1.1",
    "vue-router": "^4.3.2",
    "vue3-google-map": "^0.20.0",
    "vue3-toastify": "^0.2.1"
  },
  "devDependencies": {
    "@nuxt/eslint": "^0.3.13",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "typescript": "^5.4.5",
    "vite-plugin-eslint2": "^4.4.0"
  }
}
```
nuxt.config.ts
```
...
// ESLint options
  eslint: {
    checker: true,
    config: {
      stylistic: true
    }
  }
...
```

eslint.config.mjs
```
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  'root': true,
  'env': {
    'es2021': true,
    'browser': true,
    'node': true,
    'vue/setup-compiler-macros': true
  },
  'parser': 'vue-eslint-parser',
  'globals': {
    '$nuxt': true
  },
  'plugins': [],
  'rules': {
    '@typescript-eslint/no-unused-vars': [
      'off'
    ],
    'indent': [
      'warn',
      2,
      {
        'SwitchCase': 1
      }
    ],
    'no-console': 'error',
    // "off"
    'no-debugger': 'error',
    // "off",
    'no-unused-vars': 'off',
    'vue/html-closing-bracket-newline': 'off',
    'vue/html-indent': 'off',
    'vue/html-self-closing': [
      'warn',
      {
        'html': {
          'void': 'always',
          'normal': 'always',
          'component': 'any'
        },
        'svg': 'always',
        'math': 'always'
      }
    ],
    'vue/multi-word-component-names': 'off',
    'vue/multiline-html-element-content-newline': 0,
    'vue/require-default-prop': 'off',
    'vue/singleline-html-element-content-newline': 'off',
    'vue/script-indent': 'off'
  },
  'overrides': [
    {
      'files': [
        '*.vue'
      ],
      'rules': {
        'indent': 'off'
      }
    }
  ]
})

```

**Comment by shinGangan** [comment]
@ChamperNet 

Nice!
This eslint.config.mjs could be made simpler by understanding the [documentation](https://eslint.nuxt.com/packages/module) and the currently configured [rules](https://github.com/nuxt/eslint/tree/135207841829cba98c85c63ef788514ff7b39805/packages/eslint-config/src/flat/configs).

(I will not make any further comments as this content is inconsistent with the issue title 🙏)
