### ISSUE TITLE
docs: add how to use composer

### ISSUE THREAD

**Issue by shinGangan** [nuxt/eslint#440]
### Describe the feature

`withNuxt` and `createConfigForNuxt` can be customized using FlatConfigComposer.
(Thanks for making FlatConfigComposer 💚)

However, there is little mention of FlatConfigComposer in the document.
Therefore, it is expected that the following issues and discussions will increase.
・How should I extend Config?
・I want to set xyz as before. What should I do in that case?
・How do I use `. prepend`?

I think it would be better to include the customization method in the documentation to reduce/avoid responding to this question.

#### My Opinion

add  `Guide > Customizing the Config` section and add this page.
This page is write post simple instructions on how to use `.append`, `.override` and etc.

In addition, any questions that may be asked in the future (e.g., How should I coexist with Prettier?) will be listed separately in the FAQ.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by shinGangan** [comment]
Hi @antfu , I would appreciate it if you could comment when you have time. 🙏

Thanks for making FlatConfigComposer 💚

**Comment by antfu** [comment]
We explained here, isn't it? https://eslint.nuxt.com/packages/module#config-customizations 

If you think there are any detailed docs needed, they should also go to https://github.com/antfu/eslint-flat-config-utils#composer
