### ISSUE TITLE
Add `public` folder to the ignore list

### ISSUE THREAD

**Issue by stefanobartoletti** [nuxt/eslint#453]
### Describe the feature

Since the `public` folder is used to place files that will be copied to the built website as-is, without being processed by the bundler, I suggest to add it to the ignore list.

In some cases, it may contain files used for the hosting configuration (i.e. `_redirects` for Netlify) or for site verification (i.e. for Google Search Console) that it is probably better not to be parsed and edited by ESlint.

I can send a PR myself if this is wanted.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by sbruegel** [comment]
OK i solved it now with: 

```ts
.append( {
	ignores: [ '!server/api/*' ]
} )
```

not sure if it is the best solution. Let me know your thoughts and thanks for the big contribution to eslint!

**Comment by tcampbPPU** [comment]
I have the same situation with `app/components/public`
