### ISSUE TITLE
Upgrade to typescript-eslint v8

### ISSUE THREAD

**Issue by RihanArfan** [nuxt/eslint#456]
### Describe the feature

typescript-eslint have released v8 beta and are encouraging users to try it out. It should be stable (full release July-Sept - https://github.com/typescript-eslint/typescript-eslint/issues/9141#issuecomment-2135795100), and introduces full support for ESLint v9.

Upgrading to it is quite straight forward (and I'm happy to open a PR) but as it's a major release they've included breaking changes with rules (new + reworking old ones), which is why I think someone more familiar should handle this.

https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta/

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by merlosy** [comment]
Hi,
It feels indeed a bit odd that `@nuxt/eslint-config` start to support eslint v9, but its dependencies `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` rely on v8.
The change to do seems to be about here: https://github.com/nuxt/eslint/blob/main/packages/eslint-config/package.json#L58. (changing to alpha version).
However, I don't know the impact on the codebase. Will it still be backward compatible? maybe not..

**Comment by antfu** [comment]
We would need to wait @typescript-eslint v8 to be stable in order to ship it

**Comment by dethdkn** [comment]
Can this be shipped now @antfu? 👀
