### ISSUE TITLE
Request for support on failOnError Overlay when applying nuxt/eslint

### ISSUE THREAD

**Issue by kim1124** [nuxt/eslint#460]
### Describe the feature

I would like to apply nuxt/eslint so that if there are any issues with the code, the compilation does not proceed and an error is displayed in the browser. I have configured it as defined in the nuxt/eslint documentation, but despite the IDE and devServer detecting errors, the compilation proceeds normally and no error screen is displayed in the browser.

The code I have configured is as follows.

```
// eslint.config.mjs

import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Your custom configs here
  {
    rules: {
      'no-unused-vars': 'error'
    },
    files: ['**/*.js', '**/*.vue'] 
  }
)
```

```
// nuxt.config.ts

export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxt/eslint'],
  eslint: {
    checker: true
  }
})
```

If I intentionally cause an error as shown below, the IDE and devServer detect it properly.

![image](https://github.com/nuxt/eslint/assets/23370390/bafe7da5-c69b-4a10-81bc-673685ecbdf6)

However, despite this, the compilation does not stop, and no error screen is displayed in the browser.

![스크린샷 2024-06-27 오전 11 18 24](https://github.com/nuxt/eslint/assets/23370390/e6c9645e-6399-46f1-a1c3-40c6f8359d06)

I would like the eslint errors to be reflected in the screenshot below.

![스크린샷 2024-06-27 오전 11 20 56](https://github.com/nuxt/eslint/assets/23370390/17ef6d29-2459-45c7-9881-eebd357e0c97)

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by dsvgl** [comment]
have you installed `vite-plugin-eslint2` as mentioned in the[docs](https://eslint.nuxt.com/packages/module#dev-server-checker)?

**Comment by kim1124** [comment]
> have you installed `vite-plugin-eslint2` as mentioned in the[docs](https://eslint.nuxt.com/packages/module#dev-server-checker)?

Yes, I installed vite-plugin-eslint2 as mentioned in the documentation.

```
// package.json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "lint": "eslint .",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxt/eslint": "^0.3.13",
    "nuxt": "^3.12.2"
  },
  "devDependencies": {
    "eslint": "^8.57.0",
    "vite-plugin-checker": "^0.6.4",
    **"vite-plugin-eslint2": "^4.4.0"**
  }
}

```

**Comment by antfu** [comment]
This feature is delegated to `vite-plugin-eslint2` - if it doesn't work that way already, I'd suggest you open a request to their repo instead. Thanks!
