### ISSUE TITLE
Several built-in Nuxt globals are not defined in ESLint config, causing linter to error in JS files

### ISSUE THREAD

**Issue by adamreisnz** [nuxt/eslint#461]
### Environment

- Operating System: Darwin
- Node Version:     v22.1.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@4.3.1
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/eslint@0.3.13
- Build Modules:    -

### Package

None

### Reproduction

https://github.com/adamreisnz/nuxt-eslint-reproduction/tree/issue-461

### Describe the bug

Several built-in Nuxt globals are showing up as undefined, despite using the Nuxt ESLint module.
For example, check the files:

`nuxt.config.ts` --> `defineNuxtConfig` is marked by ESLint as not defined
`server/test.js` --> `defineEventHandler` and `readBody` are marked by ESLint as not defined

This list is probably non-exhaustive, it's just the methods I've used so far.

### Additional context

This is with a brand new Nuxt app with module enabled, and some additional globals

**Comment by antfu** [comment]
@adamreisnz Why would you add your own `@eslint/js` and `eslint-plugin-vue` configs to override Nuxt's configs?

**Comment by adamreisnz** [comment]
Why does that matter for this problem?

I don't know what base settings Nuxt uses, and I want to make sure that the
base Vue settings that I need are included.

This shouldn't affect global as they don't get overwritten.

**Comment by dsvgl** [comment]
> I don't know what base settings Nuxt uses, and I want to make sure that the
base Vue settings that I need are included.

Use the config inspector to see what is being loaded. Or check the source-code.

**Comment by adamreisnz** [comment]
I have removed the extra configuration from the `eslint.config.mjs` file to avoid it detracting from the core issue.
The problem persists, and methods calls like `defineEventHandler` and `readBody` are still flagged as not defined in `.js` files.

The error goes away in the `.ts` file, because in your config, `no-undef` has been disabled fully for TS files.

**Comment by adamreisnz** [comment]
Is there any new about a potential fix for this?

**Comment by gkkirilov** [comment]
I added globals to my eslint config, but yeah I think it should auto detect all nitro imports by default, not sure why it doesn't

```
import stylistic from '@stylistic/eslint-plugin'

import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    plugins: {
      '@stylistic': stylistic,
    },
    rules: {
      'vue/multi-word-component-names': 'off',
    },
    languageOptions: {
      globals: {
        defineEventHandler: true,
        getBody: true
      }
    }
  },
)


```
