### ISSUE TITLE
Parsing error: Unexpected token error

### ISSUE THREAD

**Issue by tobychidi** [nuxt/eslint#470]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      compatibilityDate, future, devtools, modules, image
- Runtime Modules:  @nuxt/ui@2.18.3, @nuxt/image@1.7.0, @nuxt/fonts@0.7.1, @nuxt/eslint@0.4.0, @vueuse/nuxt@10.11.0
- Build Modules:

### Package

@nuxt/eslint

### Reproduction

![image](https://github.com/user-attachments/assets/3b157076-6b63-4b75-beaa-080693569f28)
![image](https://github.com/user-attachments/assets/9bfbec13-53f2-42e9-98f4-b7e8aa724f8f)

### Describe the bug

It would seem that Typescript support is not being enabled. Even after manually adding the config

**Comment by antfu** [comment]
Did you have `typescript` installed locally? Could you share a minimal reproduction?

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by tobychidi** [comment]
Thanks @antfu. Here is a [repo](https://github.com/tobychidi/nuxt-eslint)I have just created.

**Comment by moshetanzer** [comment]
bump this also getting this - eslint is not allowing ts in vue components even when lang is explicilty set to ts

**Comment by moshetanzer** [comment]
unable to also import type

**Comment by antfu** [comment]
You you need to install `npm i -D typescript` as I mentioned, then your repro get fixed.

**Comment by moshetanzer** [comment]
Hey @antfu,

is this somehting new on latest version?

**Comment by antfu** [comment]
It was introduced in v0.4.0 (https://github.com/nuxt/eslint/commit/77bc797caef261b016aadf301334d7325b06595d) to fix https://github.com/nuxt/eslint/issues/437

Ideally it's always better to have typescript as you devDeps whenever you use typescript

**Comment by moshetanzer** [comment]
thanks a ton - maybe you should add to eslint.nuxt.com?

**Comment by tobychidi** [comment]
Hey @antfu. I have installed `-D typescript`, ran `nuxi cleanup` and reinstalled `@nuxt/eslint` module: Nothing has changed.

**Comment by tobychidi** [comment]
Somehow it is fine now. Thanks everyone. This module is super helpful.
