### ISSUE TITLE
Root in `eslint.config.mjs`

### ISSUE THREAD

**Issue by Revadike** [nuxt/eslint#495]
### Describe the feature

I'd like to commit the generated `.nuxt\eslint.config.mjs` file in my repository, so ESLint will work right away for new cloners, without having to generate it first.  I use the following in `.gitignore`:
```
.nuxt/*
!.nuxt/eslint.config.mjs
```
This works great, except for one thing: The root option. This includes the absolute path, which breaks things. Is it possible to omit this config option, or make it a relative path?

Now, that I am writing this, I'm thinking another possible solution is perhaps generate it as a postinstall step? :thinking: 
Is there a separate command for this?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by s00d** [comment]
You could at least provide some documentation on what this configFile is and why it is needed. After updating to version 0.5.6, it started ignoring all the settings in .gitignore.
@antfu 
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/c63c09ac-edd1-4d50-970e-1342442f3d1a">

**Comment by Revadike** [comment]
I don't have any issues. I noticed the `configFile` change too, but I don't think it has anything to do with the relative root change? You probably open another issue.

**Comment by s00d** [comment]
> I don't experience any issues regarding that. However, I noticed the configFile change as well, but I don't believe it's connected to the relative root change. It might be best to open a separate issue for that.

The issue is specifically with this: everything works perfectly on version 0.5.5, but the error appears immediately when updating to 0.5.6. Yes, I will create a pull request, although the issue is clearly related to this change.

**Comment by s00d** [comment]
https://github.com/nuxt/eslint/issues/496
Something like this.

**Comment by Revadike** [comment]
I mean, I think the changes were bundled. The `configFile` change may not really have anything to do with relative path change?
