### ISSUE TITLE
Module ignores .gitignore and scans ignored subfolders after updating to version 0.5.6

### ISSUE THREAD

**Issue by s00d** [nuxt/eslint#496]
### Environment

- Operating System: Darwin
- Node Version:     v20.17.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Package

@nuxt/eslint

### Reproduction

1. Clone the reproduction repository: https://github.com/s00d/nuxt-i18n-micro.
2. Change the module version to 0.5.6 in the package.json file.
3. Run npm install in the project root.
4. Execute npm run lint.

### Describe the bug

After updating to version 0.5.6, the module ignores .gitignore and scans a subfolder that should be excluded. This issue was not present in version 0.5.5.

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/c63c09ac-edd1-4d50-970e-1342442f3d1a">

### Additional context

https://github.com/nuxt/eslint/issues/496

**Comment by s00d** [comment]
https://github.com/nuxt/eslint/issues/496
Something like this.

**Comment by antfu** [comment]
This should already be fixed.
