### ISSUE TITLE
Allow custom elsint config file path, .config/eslint.config.js for example

### ISSUE THREAD

**Issue by Matheun** [nuxt/eslint#498]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.3.0`
- Nuxt Version:     `3.13.1`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `experimental`, `devtools`, `typescript`, `modules`, `css`, `postcss`, `eslint`, `formkit`, `components`, `app`, `compatibilityDate`
- Runtime Modules:  `@nuxt/eslint@0.5.6`, `@formkit/nuxt@1.6.5`
- Build Modules:    `-`

### Package

None

### Reproduction

don't have one

### Describe the bug

Could there please be a option added to set a custom config file path, currently only the generated path can be customized.

See feature request motivation:
https://github.com/pi0/config-dir

**Comment by antfu** [comment]
> Could there please be a option added to set a custom config file path, currently only the generated path can be customized.

I am not sure if I follow, what do you mean? What's the difference between them?

**Comment by Matheun** [comment]
I would like to have my `eslint.config.js` file be lokated inside a dir named `.config`, Where i put all my config files.

Right now there is no option to point to a location where the rules are defined, the only path that i can change is where the generated file will be put

**Comment by antfu** [comment]
But this module does not actually control the `eslint.config.js`, it's more on the eslint side. You can just move that file and change your config usage with `--config` https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file-resolution
