### ISSUE TITLE
Problem with Nuxt Playground linting

### ISSUE THREAD

**Issue by GaborTorma** [nuxt/eslint#501]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.8.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.11.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

Base repo from nuxt layer template with the following command:
`npx nuxi init --template layer nuxt-layer`

### Package

@nuxt/eslint

### Reproduction

https://stackblitz.com/~/github.com/GaborTorma/nuxt-eslint-playground-error

You need to see on the console. Lint automatically runs.

## 1. `vue/multi-word-component-name` rule

Default this off on nuxt pages and layers folder, but it not working in `.playground` folder.

`pages/index.vue` has no error, but the same file in playground (`.playground/pages/index.vue`) has error.

## 2. `vue/no-multiple-template-root` rule

Default this is error on nuxt pages and layers folder, but it not working in `.playground` folder.

`pages/multiple-template-root.vue` has error, but the same file in playground (`.playground/pages/multiple-template-root.vue`) has no error.

### Additional context

The problem is the `nuxt/disables/routes` and `nuxt/vue/single-root` use a generated files path instead of using a general glob path.
![2024-09-21_13-23-01](https://github.com/user-attachments/assets/f625aa8b-6876-49d0-9166-39986d467750)
The right one is the following: 
![2024-09-21_13-24-49](https://github.com/user-attachments/assets/32cdc869-ef60-4471-81e9-0d69b9c580d5)

### Logs

![2024-09-21_13-27-51](https://github.com/user-attachments/assets/2b8c6f93-6abb-4323-ba0c-6e8061d006f8)

**Comment by mrleblanc101** [comment]
Yep, I have the same issue although I use the `v4-compat` for my app, so I had to modify the layers structure a bit:
![Image](https://github.com/user-attachments/assets/d0983349-233e-4643-8610-d20f465947ae)

**Comment by mrleblanc101** [comment]
Odd, without adding the rootDir, I get 4 errors:
![Image](https://github.com/user-attachments/assets/3f5dac61-7571-4374-af6d-1775c74f68fb)
If I add the `rootDir` like in your commit, I get 6 errors:
![Image](https://github.com/user-attachments/assets/5648a4eb-bcee-4eb0-b510-2eb5ca146521)

**Comment by GaborTorma** [comment]
6 `vue/no-multiple-template-root` error is the expected result.
Do not use multiple template root in nuxt pages. More info [here](https://nuxt.com/docs/guide/directory-structure/pages#usage:~:text=Pages%20must%20have%20a%20single%20root%20element%20to%20allow%20route%20transitions%20between%20pages.%20HTML%20comments%20are%20considered%20elements%20as%20well.).

Your fixed code: 
```
<template>
    <div>
        <Teleport to="#header">Antenna</Teleport>
        <h1 class="text-2xl font-bold dark:text-brand-yellow">Antenna</h1>
    </div>
</template>
```

**Comment by mrleblanc101** [comment]
@GaborTorma Oh wait, I'm litteraly blind !
The original message was for `vue/multi-word-component-name` not `vue/no-multiple-template-root`.
Also, you're right ! Multiple root nodes are allowed for components, but not pages !
Thank you

**Comment by mrleblanc101** [comment]
@antfu Is there a guide on how to use `@nuxt/eslint` inside an app that extend a remote layer which has `@nuxt/eslint` configured ?
Currently, my eslint setup works inside my layer and inside the ./playground of that layer (because it's local/relative), but I'm not sure how I could make it work inside my app that use `c12` to clone the layer remetly.
