### ISSUE TITLE
Conflicts with eslint-plugin-import

### ISSUE THREAD

**Issue by alexcroox** [nuxt/eslint#509]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools, future, experimental, ssr, typescript, routeRules, hooks, runtimeConfig, extends, modules, sourcemap, ui, postcss, tailwindcss, vite, nitro, components, css, imports, content, ogImage, i18n
- Runtime Modules:  @nuxt/test-utils/module@3.14.2, @pinia/nuxt@0.5.5, @nuxt/ui@2.18.6, @nuxtjs/i18n@8.5.5, @nuxt/fonts@0.9.2, @vueuse/nuxt@11.1.0, @nuxt/eslint@0.5.7, nuxt-eslint-auto-explicit-import@0.1.0, @nuxt/image@1.8.1, @nuxtjs/fontaine@0.4.3, @nuxt/content@2.13.2, @codecov/nuxt-plugin@1.2.0, @nuxtjs/seo@2.0.0-rc.23, @zadigetvoltaire/nuxt-well-known@0.0.13
- Build Modules:    -
------------------------------

### Package

None

### Reproduction

```
import importPlugin from 'eslint-plugin-import'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  importPlugin.flatConfigs.recommended,
})
```

### Describe the bug

I'm trying to use `eslint-plugin-import` (https://github.com/import-js/eslint-plugin-import) and I get the error:

```
Error: ESLintFlatConfigUtils: Different instances of plugin "import" found in multiple configs:
nuxt/import/rules, import/recommended.
```

This is because import plugin is already used here (totally undocumented btw) https://github.com/nuxt/eslint/blob/main/packages/eslint-config/src/flat/configs/import.ts

I'd rather use the eslint-plugin-import plugin because:

-  In nuxt/eslint 'import/order' is gated behind enabling 'stylistic' which I don't want to use
- https://github.com/antfu/eslint-plugin-import-x is now archived and not maintained

Can I suggest we switch to eslint-plugin-import which is maintained?

**Comment by Gypsophyllite** [comment]
Same issue, I don't want to disable standalone and config a lot.🧐

**Comment by antfu** [comment]
You are linking to the wrong repo: https://github.com/un-ts/eslint-plugin-import-x which is a modern and more active version to `eslint-plugin-import`

You can always disable `import/order` explicitly if you don't want it.

I'd say `eslint-plugin-import-x` is designed to replace `eslint-plugin-import`, which I don't see the point to use the old one as the modern one is already included by Nuxt ESLint. Of course, you can do some hacks to the config array to completely remove that - or I would suggest using the standalone mode if you really don't agree with Nuxt's default (which is totally fine). I would consider this issue out-of-scope. Thanks.

**Comment by alexcroox** [comment]
I can see https://github.com/un-ts/eslint-plugin-import-x is now longer marked as archived, which makes sense if it's the replacement. Thanks

**Comment by alexcroox** [comment]
Thanks, that makes sense, I was able to enable the import/order without stylist by adding it to my own config:

`'import/order': 'error'`

**Comment by josueayala27** [comment]
https://eslint.nuxt.com/packages/module#custom-config-presets
