### ISSUE TITLE
vue/no-multiple-template-root error occurs despite using Nuxt 3 (Vue 3)

### ISSUE THREAD

**Issue by tetradice** [nuxt/eslint#511]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Package

@nuxt/eslint

### Reproduction

- [minimal example on Stackblitz](https://stackblitz.com/edit/nuxt-starter-hwdqcj?file=pages%2Findex.vue)

### Describe the bug

If I'm using Nuxt ESLint from Nuxt 3, I would think that I should be able to put multiple root elements inside the <template> of a single-file component because it uses Vue 3. But when I actually run ESLint, I get the [vue/no-multiple-template-root](https://eslint.vuejs.org/rules/no-multiple-template-root.html) error.

![Image](https://github.com/user-attachments/assets/8c052138-8f7c-4c03-a3f7-7388ba8b4024)

I used the following page as reference: https://v3-migration.vuejs.org/new/fragments.html

### Additional context

- This issue did not occur with app.vue in the root directory.
- According to [the documentation of eslint-plugin-vue](https://eslint.vuejs.org/rules/), vue/no-multiple-template-root is a rule that is checked only for Vue 2.
  ![Image](https://github.com/user-attachments/assets/807b4b1e-ff67-457d-9dcd-d5c86bc5d44b)

**Comment by dsvgl** [comment]
pages need to be single root AFAIK

**Comment by dsvgl** [comment]
https://nuxt.com/docs/guide/directory-structure/pages

![Image](https://github.com/user-attachments/assets/5ac2ff8a-90a3-4e8e-9bc9-031f13cd4c83)

**Comment by tetradice** [comment]
@dsvgl 
Sorry. I overlooked that statement. 🙇 

 I understand that it is correct that an error occurs in the pages directory because Vue 3 can use multi-root components, but Nuxt 3 pages cannot use multi-root components.

As this is working correctly as expected, I will close this issue.
