### ISSUE TITLE
Missing Github release

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/eslint#522]
I see 0.7.0 on npm, but on Github it still shows 0.6.2 as the latest version.
![Image](https://github.com/user-attachments/assets/831cfe15-89f7-4045-98a5-46826a296d4f)
![Image](https://github.com/user-attachments/assets/0246c262-9315-4c42-ad7d-e5856f6bcfa3)

**Comment by aligzl** [comment]
for me nuxt-eslint stop working too

**Comment by mrleblanc101** [comment]
@aligzl I never said it wasn't working. Why don't you open a separate issue since this is completely unrelated ?

**Comment by antfu** [comment]
It seems the tags failed to push due to my network situation in China. Should be good now, thanks for the heads up!
